grafana:
  adminPassword: "<your_password>"   # Change this!
  
  service:
    type: NodePort
    nodePort: 32000

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          options:
            path: /var/lib/grafana/dashboards/default